# .readthedocs.yaml

version: 2
formats:
  - pdf
  - epub

build:
  os: Ubuntu 24.04.1 LTS
  tools:
    python: "3.11.1"

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
